[gateway]
iii-gateway ansible_host=3.108.103.134 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern

[engine]
iii-engine ansible_host=10.0.1.10 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern ansible_ssh_common_args='-o ProxyJump=iii-gateway -o ForwardAgent=yes -o StrictHostKeyChecking=no'

[caller_worker]
iii-caller ansible_host=10.0.1.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern ansible_ssh_common_args='-o ProxyJump=iii-gateway -o ForwardAgent=yes -o StrictHostKeyChecking=no'

[inference_worker]
iii-inference ansible_host=10.0.1.30 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern ansible_ssh_common_args='-o ProxyJump=iii-gateway -o ForwardAgent=yes -o StrictHostKeyChecking=no'

[workers:children]
caller_worker
inference_worker

[private:children]
engine
workers
