#!/bin/bash
# generate_inventory.sh
# Run this after terraform apply to auto-generate the Ansible inventory
# Usage: ./scripts/generate_inventory.sh

set -euo pipefail

echo "[*] Reading Terraform outputs..."
cd "$(dirname "$0")/../terraform"

GATEWAY_IP=$(terraform output -raw gateway_public_ip)
ENGINE_IP=$(terraform output -raw engine_private_ip)
CALLER_IP=$(terraform output -raw caller_worker_private_ip)
INFERENCE_IP=$(terraform output -raw inference_worker_private_ip)

echo "[*] Gateway:          $GATEWAY_IP"
echo "[*] Engine:           $ENGINE_IP"
echo "[*] Caller worker:    $CALLER_IP"
echo "[*] Inference worker: $INFERENCE_IP"

INVENTORY_PATH="$(dirname "$0")/../ansible/inventory.ini"

cat > "$INVENTORY_PATH" <<EOF
###############################################################################
# Ansible Inventory – auto-generated by generate_inventory.sh
# Do not edit manually – re-run the script after terraform apply
###############################################################################

[gateway]
gateway ansible_host=${GATEWAY_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern

[engine]
engine ansible_host=${ENGINE_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern ansible_ssh_common_args='-o ProxyJump=ubuntu@${GATEWAY_IP} -o StrictHostKeyChecking=no'

[caller_worker]
caller ansible_host=${CALLER_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern ansible_ssh_common_args='-o ProxyJump=ubuntu@${GATEWAY_IP} -o StrictHostKeyChecking=no'

[inference_worker]
inference ansible_host=${INFERENCE_IP} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-intern ansible_ssh_common_args='-o ProxyJump=ubuntu@${GATEWAY_IP} -o StrictHostKeyChecking=no'

[private_vms:children]
engine
caller_worker
inference_worker

[all:vars]
engine_ip=${ENGINE_IP}
caller_ip=${CALLER_IP}
inference_ip=${INFERENCE_IP}
gateway_ip=${GATEWAY_IP}
EOF

echo "[✓] Inventory written to $INVENTORY_PATH"
echo ""
echo "Next step:"
echo "  cd ansible && ansible all -m ping -i inventory.ini"
